In [22]:
from PyPDF2 import PdfReader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain
import warnings
import pandas as pd
warnings.filterwarnings('ignore')
from dotenv import load_dotenv
import os
import openai
import re
from jobspy import scrape_jobs

In [2]:
pdf = 'content/resume.pdf'
pdf_reader = PdfReader(pdf)
print(pdf_reader)

<PyPDF2._reader.PdfReader object at 0x11c246bd0>

In [3]:
text = ''
for page in pdf_reader.pages:
    text += page.extract_text()

print(text)

Andre Sealy
New York, NY |(347)-461-7821 |andretsealy@gmail.com |/ewww.kidquant.com |/gtbkidquant
EDUCATION
Stevens Institute of Technology New York, NY
Masters of Science in Financial Engineering; Major GPA: 3.81 Sept 2024 - Present
Relevant Coursework: Stochastic Calculus, Pricing & Hedging, Probability Theory, Machine Learning, Deep Learning
Hunter College New York, NY
Bachelor of Arts in Mathematics; Major GPA: 3.68 Jan 2020 - Present
Relevant Coursework: Numerical Analysis, Real Analysis, Mathematical Statistics, Linear Algebra
Pace University New York, NY
Bachelor of Business Administration in Finance; Major GPA: 4.0 December 2018
Bachelor of Arts in Economics; Major GPA: 4.0
Honors: Beta Gamma Sigma, Golden Key Society
EXPERIENCE
America On Tech New York, NY
Data Science Instructor Nov 2023 - Present
•Facilitate and coordinate weekly lectures, lab projects, coding examples, graded quizzes and homework assignments.
• Design interactive weekly learning modules for more than 50 students with a primary focus on Machine Learning, Statistics,
and Data Visualization.
• Guide students in synthesizing popular data science concepts from lectures and applying them to the end of semester lab
project.
Alliance Bernstein New York, NY
Fixed Income Data Research Jan 2020 - April 2023
• Using statistical and mathematical models to develop and validate quantitative investment strategies
• Analyzing macro, fundamental, and technical drivers affecting fixed income markets
• Produce regular research reports with trade recommendations on fixed income and derivative products
RESEARCH PROJECTS
Mind The Gap: Alternative Investment Strategies For Retail Investors New York, NY
Business Honors Thesis /Independent Research Apr 2018 - May 2019
•Developed original quantitative trading strategies based on statistical analysis and market research; constructed 5 unique
trading strategies using machine learning algorithms
• Created and implemented statistical analysis to spot homogeneous trends of more than 600 equities; developed trading
strategies based on unique quantitative factors (beta, volatility, liquidity and annualized returns)
• Adjusted daily portfolio weights to achieve a maximum total average annualized portfolio return of 36.54%, maximum sharpe
ratio of 1.02, and a maximum drawdown of -18.23%
Forecasting The Destination of New Airbnb Users New York, NY
Kaggle Data Science Competition Jan 2018 - Apr 2018
• Conducted qualitative /quantitative exploratory data analysis for more than 200,000 Airbnb listings in New York City and
800,000 new users to analysis future price trends and new booking information
• Employed machine learning techniques utilizing logistic regression and random forest classifiers to predict the buying behavior
of new users within a 67% accuracy
• Implemented statistical algorithm for entrepreneurial ventures, generating an average rental income of $3,000 per month
ADDITIONAL SKILLS
Programming : Python, MATLAB, Mathematica, C ++, SQL, R, LaTeX, VBA
Machine Learning Frameworks : NumPy, Scikit-learn, Pandas, TensorFlow, Matplotlib, PyTorch
Software : Excel, PowerPoint, Word, Access, Power BI
Languages : English (Native), Mandarin (Intermediate Speaking Proficiency), Cantonese (Basic)

In [4]:
# split the long text into small chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=700,
                                               chunk_overlap=200,
                                               length_function=len)

chunks = text_splitter.split_text(text)
chunks

['Andre Sealy\nNew York, NY |(347)-461-7821 |andretsealy@gmail.com |/ewww.kidquant.com |/gtbkidquant\nEDUCATION\nStevens Institute of Technology New York, NY\nMasters of Science in Financial Engineering; Major GPA: 3.81 Sept 2024 - Present\nRelevant Coursework: Stochastic Calculus, Pricing & Hedging, Probability Theory, Machine Learning, Deep Learning\nHunter College New York, NY\nBachelor of Arts in Mathematics; Major GPA: 3.68 Jan 2020 - Present\nRelevant Coursework: Numerical Analysis, Real Analysis, Mathematical Statistics, Linear Algebra\nPace University New York, NY\nBachelor of Business Administration in Finance; Major GPA: 4.0 December 2018\nBachelor of Arts in Economics; Major GPA: 4.0',
 'Pace University New York, NY\nBachelor of Business Administration in Finance; Major GPA: 4.0 December 2018\nBachelor of Arts in Economics; Major GPA: 4.0\nHonors: Beta Gamma Sigma, Golden Key Society\nEXPERIENCE\nAmerica On Tech New York, NY\nData Science Instructor Nov 2023 - Present\n•Facilitate and coordinate weekly lectures, lab projects, coding examples, graded quizzes and homework assignments.\n• Design interactive weekly learning modules for more than 50 students with a primary focus on Machine Learning, Statistics,\nand Data Visualization.\n• Guide students in synthesizing popular data science concepts from lectures and applying them to the end of semester lab\nproject.',
 'and Data Visualization.\n• Guide students in synthesizing popular data science concepts from lectures and applying them to the end of semester lab\nproject.\nAlliance Bernstein New York, NY\nFixed Income Data Research Jan 2020 - April 2023\n• Using statistical and mathematical models to develop and validate quantitative investment strategies\n• Analyzing macro, fundamental, and technical drivers affecting fixed income markets\n• Produce regular research reports with trade recommendations on fixed income and derivative products\nRESEARCH PROJECTS\nMind The Gap: Alternative Investment Strategies For Retail Investors New York, NY\nBusiness Honors Thesis /Independent Research Apr 2018 - May 2019',
 'RESEARCH PROJECTS\nMind The Gap: Alternative Investment Strategies For Retail Investors New York, NY\nBusiness Honors Thesis /Independent Research Apr 2018 - May 2019\n•Developed original quantitative trading strategies based on statistical analysis and market research; constructed 5 unique\ntrading strategies using machine learning algorithms\n• Created and implemented statistical analysis to spot homogeneous trends of more than 600 equities; developed trading\nstrategies based on unique quantitative factors (beta, volatility, liquidity and annualized returns)\n• Adjusted daily portfolio weights to achieve a maximum total average annualized portfolio return of 36.54%, maximum sharpe',
 '• Adjusted daily portfolio weights to achieve a maximum total average annualized portfolio return of 36.54%, maximum sharpe\nratio of 1.02, and a maximum drawdown of -18.23%\nForecasting The Destination of New Airbnb Users New York, NY\nKaggle Data Science Competition Jan 2018 - Apr 2018\n• Conducted qualitative /quantitative exploratory data analysis for more than 200,000 Airbnb listings in New York City and\n800,000 new users to analysis future price trends and new booking information\n• Employed machine learning techniques utilizing logistic regression and random forest classifiers to predict the buying behavior\nof new users within a 67% accuracy',
 '• Employed machine learning techniques utilizing logistic regression and random forest classifiers to predict the buying behavior\nof new users within a 67% accuracy\n• Implemented statistical algorithm for entrepreneurial ventures, generating an average rental income of $3,000 per month\nADDITIONAL SKILLS\nProgramming : Python, MATLAB, Mathematica, C ++, SQL, R, LaTeX, VBA\nMachine Learning Frameworks : NumPy, Scikit-learn, Pandas, TensorFlow, Matplotlib, PyTorch\nSoftware : Excel, PowerPoint, Word, Access, Power BI\nLanguages : English (Native), Mandarin (Intermediate Speaking Proficiency), Cantonese (Basic)']

In [5]:
chunks[0]

'Andre Sealy\nNew York, NY |(347)-461-7821 |andretsealy@gmail.com |/ewww.kidquant.com |/gtbkidquant\nEDUCATION\nStevens Institute of Technology New York, NY\nMasters of Science in Financial Engineering; Major GPA: 3.81 Sept 2024 - Present\nRelevant Coursework: Stochastic Calculus, Pricing & Hedging, Probability Theory, Machine Learning, Deep Learning\nHunter College New York, NY\nBachelor of Arts in Mathematics; Major GPA: 3.68 Jan 2020 - Present\nRelevant Coursework: Numerical Analysis, Real Analysis, Mathematical Statistics, Linear Algebra\nPace University New York, NY\nBachelor of Business Administration in Finance; Major GPA: 4.0 December 2018\nBachelor of Arts in Economics; Major GPA: 4.0'

In [6]:

load_dotenv()
openai.api_key = os.environ["OPENAI_API_KEY"]

def openai_function(openai_api_key, chunks, analyze):

    # Using OpenAI service for embedding
    embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)

    # Facebook AI Similarity Search library help us to convert text data to numerical vector
    vectorstores = FAISS.from_texts(chunks, embedding=embeddings)

    # compares the query and chunks, enabling the selection of the top 'K' most similiar chunks based on their similarity scores.
    docs = vectorstores.similarity_search(query=analyze, k=3)

    # creates an OpenAI object, using the ChatGPT 4 
    llm = ChatOpenAI(model='gpt-4o', api_key=openai_api_key)

    # question-answering (QA) pipeline, making use of the load_qa_chain function
    chain = load_qa_chain(llm=llm, chain_type='stuff')

    response = chain.run(input_documents=docs, question=analyze)
    return response

In [7]:
def resume_summary(query_with_chunks):
    query = f''' need to detailed summarization of below resume and finally conclude them

                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                {query_with_chunks}
                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                '''
    return query

summary = resume_summary(query_with_chunks=chunks)
summary_result = openai_function(openai_api_key=openai.api_key, chunks=chunks, analyze=summary)
print(summary_result)

Andre Sealy is a highly educated individual currently based in New York, NY. He is pursuing a Masters of Science in Financial Engineering at Stevens Institute of Technology, maintaining a major GPA of 3.81, and is expected to complete it by September 2024. His coursework includes Stochastic Calculus, Pricing & Hedging, Probability Theory, Machine Learning, and Deep Learning. Andre also holds a Bachelor of Arts in Mathematics from Hunter College with a major GPA of 3.68, and a Bachelor of Business Administration in Finance as well as a Bachelor of Arts in Economics from Pace University, both with a perfect major GPA of 4.0. He received honors such as being a member of Beta Gamma Sigma and the Golden Key Society.

Professionally, Andre has experience as a Data Science Instructor at America On Tech, where he has been working since November 2023. In this role, he facilitates lectures and projects, focusing on Machine Learning, Statistics, and Data Visualization for over 50 students. Before this, he worked at Alliance Bernstein in Fixed Income Data Research from January 2020 to April 2023, where he developed quantitative investment strategies and produced research reports on fixed income markets.

Andre has also engaged in several research projects. Notably, he completed a Business Honors Thesis titled "Mind The Gap: Alternative Investment Strategies For Retail Investors" where he developed quantitative trading strategies and achieved significant portfolio returns. He also participated in a Kaggle Data Science Competition, forecasting Airbnb user behavior with machine learning techniques.

His additional skills include proficiency in programming languages such as Python, MATLAB, and SQL, and machine learning frameworks like TensorFlow and PyTorch. He is proficient in a variety of software tools and has language skills in Mandarin and Cantonese.

In conclusion, Andre Sealy is a well-rounded individual with a strong academic background and practical experience in finance, data science, and machine learning. His diverse skill set and achievements make him a valuable asset in the fields of financial engineering and data research.

In [ ]:
def resume_strength(query_with_chunks):
    query = f'''need to detailed analysis and explain of the strength of below resume and finally conclude them
                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                {query_with_chunks}
                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                '''
    return query

strengths = resume_strength(query_with_chunks=chunks)
strengths_result = openai_function(openai_api_key=openai.api_key, chunks=chunks, analyze=strengths)
print(strengths_result)

In [ ]:
def resume_weakness(query_with_chunks):
    query = f'''need to detailed analysis and explain of the weakness of below resume and how to improve make a better resume.

                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                {query_with_chunks}
                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                '''
    return query

weakness = resume_weakness(query_with_chunks=summary_result)
result_weakness = openai_function(openai_api_key=openai.api_key, chunks=chunks, analyze=weakness)
print(result_weakness)

In [ ]:
def job_title_suggestion(query_with_chunks):

    query = f''' what are the job roles i apply to likedin based on below?
                  
                  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                  {query_with_chunks}
                  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                '''
    return query

suggestion = job_title_suggestion(query_with_chunks=summary_result)
result_suggestion = openai_function(openai_api_key=openai.api_key, chunks=chunks, analyze=suggestion)
print(result_suggestion)

In [10]:
def job_title_prompt(query_with_chunks):
    query = f'''Based on my resume, come up with some job roles that would best fit my skills and abilities.
                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                {query_with_chunks}

                """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
                '''
    return query

job_prompt = job_title_prompt(query_with_chunks=summary_result)
jobs = openai_function(openai_api_key=openai.api_key, chunks=chunks, analyze=job_prompt)
print(jobs)

Based on the information provided in your resume, here are some potential job roles that would best fit your skills and abilities:

1. **Quantitative Analyst**: Your strong background in financial engineering, mathematics, and machine learning makes you an ideal candidate for roles that involve developing and implementing quantitative models for trading, risk management, or investment strategies.

2. **Data Scientist in Finance**: With your experience in machine learning, data science, and financial markets, a role that focuses on analyzing financial data to develop predictive models and insights would be a great fit.

3. **Financial Engineer**: Your education and experience align well with roles that involve designing and implementing financial products or systems, particularly those using advanced quantitative and computational techniques.

4. **Machine Learning Engineer**: Given your expertise in machine learning frameworks such as TensorFlow and PyTorch, a role that involves building and deploying machine learning models in a financial context could be suitable.

5. **Investment Research Analyst**: Your background in analyzing macro, fundamental, and technical drivers affecting markets, as well as producing research reports, positions you well for roles that focus on generating investment insights and recommendations.

6. **Risk Management Analyst**: With your knowledge of stochastic calculus, probability theory, and quantitative finance, a role in risk management, where you can apply these skills to assess and mitigate financial risks, could be a good match.

7. **Financial Data Scientist**: Combining your data science skills with your financial knowledge, you could excel in roles that involve analyzing financial datasets to extract actionable insights and develop data-driven strategies.

8. **Instructor or Educator in Data Science/Finance**: Given your experience as a Data Science Instructor, you could consider roles in academia or training institutions, focusing on teaching and developing curricula in finance and data science.

These roles leverage your strong analytical skills, technical expertise, and understanding of financial markets, allowing you to contribute effectively to organizations in the finance and data sectors.

In [12]:
jobs_list = re.findall(r"\*\*(.*?)\*\*", jobs)

Quantitative Analyst
Data Scientist in Finance
Financial Engineer
Machine Learning Engineer
Investment Research Analyst
Risk Management Analyst
Financial Data Scientist
Instructor or Educator in Data Science/Finance

In [20]:
jobs_scraped = scrape_jobs(
    site_name=[
        "indeed",
        "linkedin",
        "glassdoor",
        "google",
    ],
    search_term="Quantitative Analyst",
    location="New York, NY",
    max_results=20,
    country_indeed="USA",
)

jobs_scraped.head()

                 id       site  ... vacancy_count work_from_home_type
0  gd-1009722344786  glassdoor  ...          None                None
1  gd-1009722858798  glassdoor  ...          None                None
2  gd-1009722098356  glassdoor  ...          None                None
3  gd-1009721946928  glassdoor  ...          None                None
4  gd-1009720720937  glassdoor  ...          None                None

[5 rows x 34 columns]

In [39]:
# Loop over the strings in jobs_list and run the function scrape_jobs
for job in jobs_list:
    # Scrape jobs for each job title in jobs_list
    jobs_scraped_for_job = scrape_jobs(
        site_name=[
            "indeed",
            "linkedin",
            "glassdoor",
            "google",
        ],
        search_term=job,
        location="New York, NY",
        max_results=20,
        country_indeed="USA",
    )

    jobs_scraped_for_job['job_type'] = job

    # Merge the output with the previous dataframe
    jobs_scraped = pd.concat([jobs_scraped, jobs_scraped_for_job], ignore_index=True)


jobs_scraped = jobs_scraped[
    [
        # "id",
        "site",
        "job_url",
        "title",
        "company",
        "date_posted",
        "job_type",
        "interval",
        "min_amount",
        "max_amount",
        "currency",
        "description",
    ]
]

jobs_scraped.iloc[:25]

         site  ...                                        description
0   glassdoor  ...  **WORK OPTION:** The NBA currently provides el...
1   glassdoor  ...  **Pay:** $30/\-Hour\n  \n  \n\nShift; Mon\-Fri...
2   glassdoor  ...  **Data Analyst– New York, NY \- Day**\n-------...
3   glassdoor  ...  ### **Job Description:**\n\n**Quantitative Ris...
4   glassdoor  ...  Universal Ads, a part of Comcast, enables any ...
5   glassdoor  ...  **JOB DESCRIPTION**  \n\nJoin our team as an A...
6   glassdoor  ...  **You Lead the Way. We’ve Got Your Back.**\n\n...
7   glassdoor  ...  United States \- New York\nQuantitative Analys...
8   glassdoor  ...  **NYU Grossman School of Medicine** is one of ...
9   glassdoor  ...  **Job Description**\n-------------------\n\n##...
10  glassdoor  ...  Citigroup Global Markets Inc. seeks a Quantita...
11  glassdoor  ...  Role: Business Analyst Location: Brooklyn, NY(...
12  glassdoor  ...  **Job Description**\n-------------------\n\n##...
13  glassdoor  ...  **Asset \& Wealth Management \- Analyst Quanti...
14  glassdoor  ...  **Job description**\n-------------------\n\n\n...
15     google  ...  Front Office Quantitative Analyst, Vice Presid...
16     google  ...  The Risk Research, Analysis, and Measurement t...
17     google  ...  We are working with a Crypto Trading start-up ...
18     google  ...  Quantitative Developer - Cash Equities\n\nA le...
19     google  ...  Job Description\nRole Summary\nAt Citadel Secu...
20     google  ...  Risk Quant -Methodology\n\nLocation: midtown N...
21     google  ...  About this role\n\nBlackRock is one of the wor...
22     google  ...  THE ROLE\n\nWe seek a seasoned Credit Quant. Y...
23     google  ...  Summary:\n\nA front office quantitative analys...
24     google  ...  Job Opportunity: Linear Rates Quant Analyst at...

[25 rows x 11 columns]